# Generated by Django 3.1.7 on 2021-04-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('anel.svg', 'Anel'), ('colar.svg', 'Colar'), ('brico.svg', 'Brinco'), ('envio.svg', 'Envio')], max_length=9, verbose_name='Icone'),
        ),
    ]
